{
  "hash": "f55bc26ce84f54931c1ee5aad02d4e3a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1\"\nauthor: \"JIN JIAYING\"\ndate: \"Feburary 6,2026\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# Overview\n\nA survey aimed to manage students and factors affecting their learning outcomes was conducted in Vietnam National University (VNU). The survey is faced to both current student and alumni in VNU from March to June 2023, and there were 2170 valid feedback.\n\nThis visual analysis will transform the survey data into student learning outcome insights by identifying patterns, trends, and relationships within responses.\n\n\n# Loading Package\n\nThe following R packages are loaded using pacman::p_load() function.\n\n::: {.panel-tabset}\n## Code Chunk\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  gt, tidyverse, readxl, skimr,\n  ggdist, ggridges, ggthemes, colorspace,\n  scales, cowplot,\n  seriation, dendextend, heatmaply,\n  viridis)\n```\n:::\n\n\n## Packages\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ehxssbkhub\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ehxssbkhub table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ehxssbkhub thead, #ehxssbkhub tbody, #ehxssbkhub tfoot, #ehxssbkhub tr, #ehxssbkhub td, #ehxssbkhub th {\n  border-style: none;\n}\n\n#ehxssbkhub p {\n  margin: 0;\n  padding: 0;\n}\n\n#ehxssbkhub .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ehxssbkhub .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ehxssbkhub .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ehxssbkhub .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ehxssbkhub .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ehxssbkhub .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ehxssbkhub .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ehxssbkhub .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ehxssbkhub .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ehxssbkhub .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ehxssbkhub .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ehxssbkhub .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ehxssbkhub .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ehxssbkhub .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ehxssbkhub .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehxssbkhub .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ehxssbkhub .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ehxssbkhub .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ehxssbkhub .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehxssbkhub .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ehxssbkhub .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehxssbkhub .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ehxssbkhub .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehxssbkhub .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ehxssbkhub .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehxssbkhub .gt_left {\n  text-align: left;\n}\n\n#ehxssbkhub .gt_center {\n  text-align: center;\n}\n\n#ehxssbkhub .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ehxssbkhub .gt_font_normal {\n  font-weight: normal;\n}\n\n#ehxssbkhub .gt_font_bold {\n  font-weight: bold;\n}\n\n#ehxssbkhub .gt_font_italic {\n  font-style: italic;\n}\n\n#ehxssbkhub .gt_super {\n  font-size: 65%;\n}\n\n#ehxssbkhub .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ehxssbkhub .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ehxssbkhub .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ehxssbkhub .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ehxssbkhub .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ehxssbkhub .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ehxssbkhub .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ehxssbkhub .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ehxssbkhub div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style=\"font-size: 22px; font-weight: bold;\">Software and R packages used in this analysis</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-size: 16px; font-weight: bold; background-color: #F2F2F2;\" scope=\"col\" id=\"Package\">Package</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-size: 16px; font-weight: bold; background-color: #F2F2F2;\" scope=\"col\" id=\"Description\">Purpose in workflow</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"2\" class=\"gt_group_heading\" style=\"font-size: 14px; font-weight: bold; background-color: #EFEFEF; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #BDBDBD;\" scope=\"colgroup\" id=\"R packages used\">R packages used</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"R packages used  Package\" class=\"gt_row gt_left\">tidyverse</td>\n<td headers=\"R packages used  Description\" class=\"gt_row gt_left\">Core tools for data wrangling, reshaping, and visualisation.</td></tr>\n    <tr><td headers=\"R packages used  Package\" class=\"gt_row gt_left\">readxl</td>\n<td headers=\"R packages used  Description\" class=\"gt_row gt_left\">Reads Excel files (.xls/.xlsx) into R.</td></tr>\n    <tr><td headers=\"R packages used  Package\" class=\"gt_row gt_left\">skimr</td>\n<td headers=\"R packages used  Description\" class=\"gt_row gt_left\">Compact data summaries (missingness, distributions, descriptive stats).</td></tr>\n    <tr><td headers=\"R packages used  Package\" class=\"gt_row gt_left\">pacman</td>\n<td headers=\"R packages used  Description\" class=\"gt_row gt_left\">Loads/installs packages via p_load() for reproducibility.</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"2\" class=\"gt_group_heading\" style=\"font-size: 14px; font-weight: bold; background-color: #EFEFEF; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #BDBDBD;\" scope=\"colgroup\" id=\"Data visualization (ggplot extensions)\">Data visualization (ggplot extensions)</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Data visualization (ggplot extensions)  Package\" class=\"gt_row gt_left\">ggplot2 (via tidyverse)</td>\n<td headers=\"Data visualization (ggplot extensions)  Description\" class=\"gt_row gt_left\">Primary plotting system used to build all figures.</td></tr>\n    <tr><td headers=\"Data visualization (ggplot extensions)  Package\" class=\"gt_row gt_left\">ggdist</td>\n<td headers=\"Data visualization (ggplot extensions)  Description\" class=\"gt_row gt_left\">Distribution/interval geoms for uncertainty and comparisons.</td></tr>\n    <tr><td headers=\"Data visualization (ggplot extensions)  Package\" class=\"gt_row gt_left\">ggridges</td>\n<td headers=\"Data visualization (ggplot extensions)  Description\" class=\"gt_row gt_left\">Ridge plots for comparing distributions across groups.</td></tr>\n    <tr><td headers=\"Data visualization (ggplot extensions)  Package\" class=\"gt_row gt_left\">ggthemes</td>\n<td headers=\"Data visualization (ggplot extensions)  Description\" class=\"gt_row gt_left\">Predefined themes for consistent plot styling.</td></tr>\n    <tr><td headers=\"Data visualization (ggplot extensions)  Package\" class=\"gt_row gt_left\">colorspace</td>\n<td headers=\"Data visualization (ggplot extensions)  Description\" class=\"gt_row gt_left\">Colour tools for palette control and consistent visual design.</td></tr>\n    <tr><td headers=\"Data visualization (ggplot extensions)  Package\" class=\"gt_row gt_left\">cowplot</td>\n<td headers=\"Data visualization (ggplot extensions)  Description\" class=\"gt_row gt_left\">Combine, align, and annotate multiple ggplots in one figure.</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"2\" class=\"gt_group_heading\" style=\"font-size: 14px; font-weight: bold; background-color: #EFEFEF; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #BDBDBD;\" scope=\"colgroup\" id=\"Association and clustering / heatmap utilities\">Association and clustering / heatmap utilities</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Association and clustering / heatmap utilities  Package\" class=\"gt_row gt_left\">seriation</td>\n<td headers=\"Association and clustering / heatmap utilities  Description\" class=\"gt_row gt_left\">Reorders rows/columns to reveal structure in matrices (useful for heatmaps).</td></tr>\n    <tr><td headers=\"Association and clustering / heatmap utilities  Package\" class=\"gt_row gt_left\">dendextend</td>\n<td headers=\"Association and clustering / heatmap utilities  Description\" class=\"gt_row gt_left\">Manipulates and customises dendrograms (reorder, cut, style).</td></tr>\n    <tr><td headers=\"Association and clustering / heatmap utilities  Package\" class=\"gt_row gt_left\">heatmaply</td>\n<td headers=\"Association and clustering / heatmap utilities  Description\" class=\"gt_row gt_left\">Creates interactive heatmaps (plotly-based).</td></tr>\n    <tr><td headers=\"Association and clustering / heatmap utilities  Package\" class=\"gt_row gt_left\">viridis</td>\n<td headers=\"Association and clustering / heatmap utilities  Description\" class=\"gt_row gt_left\">Perceptually uniform, colourblind-friendly palettes.</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n\n# The Data\n\nThe survey data is the \"Database paper\" file in excel format and related \"CODEBOOK\" file in word format, retrieved from [Mendelay Data](https://data.mendeley.com/datasets/23ppcdbmhc/1).\n\n## Importing Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- read_excel(\"C:/Users/jiayi/Documents/SMU/26 Jan Term/ISSS608_Visual_Analytics_and_Applications/ISSS608_Lwn0170/data/TE01_data.xlsx\", sheet = 1)\n```\n:::\n\n\n\n# Data pre-processing\n\nBefore using survey data, we first take a look and have a further study of the dataset.\n\nThe dataset consists of 2,170 rows and 22 columns.\n\n## Transformation\n\nThe survey data were initially encoded numerically,where discrete integers represent categorical responses (e.g., 1 = “Male”, 2 = “Female”). Based on the CODEBOOK, these variables were transformed into factors for nominal categories and ordered factors for ordinal scales. \n\nIn this case, the dataset preserves the measurement level of each variable, enforces a meaningful ordering for ordinal responses, and also generates correctly ordered axes with interpretable labels in visual analysis later.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey <- raw %>%\n  mutate(\n    Year = factor(\n      Year, levels = 1:5,\n      labels = c(\"First-year\", \"Second-year\", \"Third-year\", \"Fourth-year\", \"Graduated\"),\n      ordered = TRUE\n    ),\n    \n    Gender = factor(Gender, levels = c(1,2), labels = c(\"Male\", \"Female\")),\n    \n    Policy_Stu   = factor(Policy_Stu,   levels = c(1,2), labels = c(\"Yes\",\"No\")),\n    Minority_Stu = factor(Minority_Stu, levels = c(1,2), labels = c(\"Yes\",\"No\")),\n    Poor_Stu     = factor(Poor_Stu,     levels = c(1,2), labels = c(\"Yes\",\"No\")),\n    \n    Father_Edu = factor(\n      Father_Edu, levels = 1:6,\n      labels = c(\"Primary school\", \"Secondary school\", \"High school\", \"College school\", \"University/graduate education\", \"Other\"),\n      ordered = TRUE\n    ),\n    Mother_Edu = factor(\n      Mother_Edu, levels = 1:6,\n      labels = c(\"Primary school\", \"Secondary school\", \"High school\", \"College school\", \"University/graduate education\", \"Other\"),\n      ordered = TRUE\n    ),\n    \n    Father_Occupation = factor(\n      Father_Occupation, levels = 1:5,\n      labels = c(\"Government employee\", \"Self-employment\", \"Freelance\", \"Other\", \"Not public\")\n    ),\n    Mother_Occupation = factor(\n      Mother_Occupation, levels = 1:5,\n      labels = c(\"Government employee\", \"Self-employment\", \"Freelance\", \"Other\", \"Not public\")\n    ),\n    \n    Time_Friends = factor(\n      Time_Friends, levels = 1:5,\n      labels = c(\"under 1 hour\", \"1 to <2 hours\", \"2 to <3 hours\", \"3 to <4 hours\", \"over 4 hours\"),\n      ordered = TRUE\n    ),\n    Time_SocicalMedia = factor(\n      Time_SocicalMedia, levels = 1:5,\n      labels = c(\"under 1 hour\", \"1 to <2 hours\", \"2 to <3 hours\", \"3 to <4 hours\", \"over 4 hours\"),\n      ordered = TRUE\n    ),\n    Time_Studying = factor(\n      Time_Studying, levels = 1:5,\n      labels = c(\"under 2 hours\", \"2 to <4 hours\", \"4 to <6 hours\", \"6 to <8 hours\", \"over 8 hour\"),\n      ordered = TRUE\n    ),\n    \n    GPA = factor(\n      GPA, levels = 1:5,\n      labels = c(\"Poor\", \"Average\", \"Fair\", \"Good\", \"Excellent\"),\n      ordered = TRUE\n    ),\n    \n    Adapt_Learning_Uni = factor(\n      Adapt_Learning_Uni, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE\n    ),\n    Study_Methods = factor(\n      Study_Methods, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE\n    ),\n    SupportOf_Uni = factor(\n      SupportOf_Uni, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE\n    ),\n    SupportOf_Lec = factor(\n      SupportOf_Lec, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE\n    ),\n    Facilitie_Uni = factor(\n      Facilitie_Uni, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE\n    ),\n    Quality_Lecturer = factor(\n      Quality_Lecturer, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE\n    ),\n    TrainingCurriculum = factor(\n      TrainingCurriculum, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE\n    ),\n    Competitive_Class = factor(\n      Competitive_Class, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE\n    ),\n    InfuenceF_Friends = factor(\n      InfuenceF_Friends, levels = 1:5,\n      labels = c(\"Not at all\", \"Little\", \"Moderate\", \"Quite\", \"Very\"),\n      ordered = TRUE)\n  )\n```\n:::\n\n\n## Data Screening\n\nFollowing the conceptual framework of the [original survey study](https://www.sciencedirect.com/science/article/pii/S2352340925001702#bib0001), all explanatory variables were grouped into two categories: (A) demographic factors, and (B) motivation and external learning factors. GPA is treated separately as the outcome variable, representing student learning performance.\n\nBefore visualising the survey results, table() was used to inspect the frequency distribution of each categorical variable (including missing values). \n\nThis quick check confirms whether coded responses follow the CODEBOOK, reveals empty categories or imbalanced groups, and helps identify potential data issues (e.g., unexpected codes) that could affect interpretation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Demographic Factors#\nA_vars <- c(\n  \"Year\", \"Gender\", \"Policy_Stu\", \"Minority_Stu\", \"Poor_Stu\", \"Father_Edu\", \"Mother_Edu\", \"Father_Occupation\", \"Mother_Occupation\", \"Time_Friends\", \"Time_SocicalMedia\", \"Time_Studying\"\n  )\n\n#Motivation/External Factors#\nB_vars <- c(\n  \"Adapt_Learning_Uni\", \"Study_Methods\", \"SupportOf_Uni\", \"SupportOf_Lec\", \"Facilitie_Uni\", \"Quality_Lecturer\", \"TrainingCurriculum\", \"Competitive_Class\", \"InfuenceF_Friends\"\n  )\n\n#Outcome\noutcome_var <- \"GPA\"\n```\n:::\n\n::: {.panel-tabset}\n## Group A: Demographic Factors\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================\nVariable: Year \n============================\n\n First-year Second-year  Third-year Fourth-year   Graduated \n          0           0         135         441        1594 \n\n============================\nVariable: Gender \n============================\n\n  Male Female \n   240   1930 \n\n============================\nVariable: Policy_Stu \n============================\n\n Yes   No \n 766 1404 \n\n============================\nVariable: Minority_Stu \n============================\n\n Yes   No \n 129 2041 \n\n============================\nVariable: Poor_Stu \n============================\n\n Yes   No \n  86 2084 \n\n============================\nVariable: Father_Edu \n============================\n\n               Primary school              Secondary school \n                          120                           274 \n                  High school                College school \n                          603                           370 \nUniversity/graduate education                         Other \n                          643                           160 \n\n============================\nVariable: Mother_Edu \n============================\n\n               Primary school              Secondary school \n                          125                           294 \n                  High school                College school \n                          592                           495 \nUniversity/graduate education                         Other \n                          502                           162 \n\n============================\nVariable: Father_Occupation \n============================\n\nGovernment employee     Self-employment           Freelance               Other \n                514                 565                 650                 409 \n         Not public \n                 32 \n\n============================\nVariable: Mother_Occupation \n============================\n\nGovernment employee     Self-employment           Freelance               Other \n                491                 557                 695                 405 \n         Not public \n                 22 \n\n============================\nVariable: Time_Friends \n============================\n\n under 1 hour 1 to <2 hours 2 to <3 hours 3 to <4 hours  over 4 hours \n          557           785           590           152            86 \n\n============================\nVariable: Time_SocicalMedia \n============================\n\n under 1 hour 1 to <2 hours 2 to <3 hours 3 to <4 hours  over 4 hours \n          229           735           634           306           266 \n\n============================\nVariable: Time_Studying \n============================\n\nunder 2 hours 2 to <4 hours 4 to <6 hours 6 to <8 hours   over 8 hour \n           17            47            78           245          1783 \n```\n\n\n:::\n:::\n\n## Group B: Motivation/External Factors\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================\nVariable: Adapt_Learning_Uni \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        70        152        954        606        388 \n\n============================\nVariable: Study_Methods \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        33        120        869        674        474 \n\n============================\nVariable: SupportOf_Uni \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        51         61        553        675        830 \n\n============================\nVariable: SupportOf_Lec \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        20         28        448        706        968 \n\n============================\nVariable: Facilitie_Uni \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        36        131        399        677        927 \n\n============================\nVariable: Quality_Lecturer \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        16         24        342        636       1152 \n\n============================\nVariable: TrainingCurriculum \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        12         45        465        779        869 \n\n============================\nVariable: Competitive_Class \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        13         76        629        772        680 \n\n============================\nVariable: InfuenceF_Friends \n============================\n\nNot at all     Little   Moderate      Quite       Very \n        20         82        707        797        564 \n```\n\n\n:::\n:::\n\n## Outcome: GPA\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================\nVariable: GPA \n============================\n\n     Poor   Average      Fair      Good Excellent \n       73       109      1189       692       107 \n```\n\n\n:::\n:::\n\n:::\n\nThe result shows an imbalanced distribution in study year and gender. There were no first- or second-year respondents in the survey responses, and female students substantially outnumbered male students. \n\nTo improve interpretability and avoid misleading comparisons driven by sparse categories, the study-year variable was recoded into two groups: “current students (3rd/4th year)” and “graduated.” Gender was retained but interpreted with caution due to the uneven group sizes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_final <- survey %>%\n  mutate(\n    Year_group = case_when(\n      Year %in% c(\"Third-year\", \"Fourth-year\") ~ \"Current (3rd/4th)\",\n      Year == \"Graduated\" ~ \"Graduated\",\n      TRUE ~ NA_character_\n    ) %>%\n      factor(levels = c(\"Current (3rd/4th)\", \"Graduated\"))\n  )\n\ntable(survey_final$Year_group, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCurrent (3rd/4th)         Graduated \n              576              1594 \n```\n\n\n:::\n:::\n\n\n\n# Exploratory Data Analysis - \n\n##  Distribution of Students’ Learning Performance (GPA)\n\nGPA is measured as an ordered categorical variable rather than a continuous numeric measure, a bar chart is more appropriate for visualizing its frequency distributions and allows clearer comparison across GPA groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_dist <- count(survey_final, GPA)\n\nggplot(gpa_dist, aes(x = GPA, y = n)) +\n  geom_col() +\n  geom_text(aes(label = n), hjust = -0.1) +\n  coord_flip() +\n  labs(\n    title = \"Distribution of GPA\",\n    x = \"GPA category\",\n    y = \"Number of students\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](TE01_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\nThe distribution of GPA shows a clear concentration in the middle categories. The majority of respondents fall into the “Fair” (n = 1189) and “Good” (n = 692) categories, while relatively few students are located at the extremes.\n\nThis indicates that learning performance in the survey is clustered around moderate achievement levels rather than polarized at either the high or low end.\n\nThis pattern suggests that explanatory factors are more likely to manifest as subtle distributional shifts rather than dramatic polarization effects. Thus, for subsequent analyses, we will focus on examining proportional differences across GPA levels rather than assuming large structural divides.\n\n\n## Relationship between Learning Outcome and Group A: Demographic Factors\n\nTo improve interpretability, Group A variables are separated into two sets based on their measurement structure. \n\nThe first set contains binary variables only, which are well-suited for 100% stacked bar charts because the proportional composition remains easy to compare across GPA categories. \n\nThe second set contains multi-level ordinal or categorical variables. For these variables, stacked bars become visually cluttered due to many categories and colors. Therefore, heatmap is used to highlight distributional shifts across GPA levels more clearly while reducing unnecessary visual noise.\n\nLast but not least, percentages rather than count nnumber will be used due to the data sizes differ between groups and GPA levels.\n\n### Proportional Composition of Binary Group A Variables by GPA\n\n**Binary Group A variables (2 levels):**\n\n- Year_group\n- Gender\n- Policy_Stu\n- Minority_Stu\n- Poor_Stu\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_by_gpa <- dplyr::count(survey_final, GPA, name = \"n\")\n\n\np_year <- ggplot(survey_final, aes(x = GPA, fill = Year_group)) +\n  geom_bar(position = \"fill\") +\n  geom_text(data = n_by_gpa,\n            aes(x = GPA, y = 1.08, label = paste0(\"n=\", n)),\n            inherit.aes = FALSE, size = 2.5) +\n  scale_y_continuous(labels = percent) +\n  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 12)) +\n  scale_fill_viridis_d(option = \"C\", begin = 0.1, end = 0.9, name = \"Year_group\") +\n  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +\n  labs(y = \"Proportion\", title = \"Year_group\")\n\np_gender <- ggplot(survey_final, aes(x = GPA, fill = Gender)) +\n  geom_bar(position = \"fill\") +\n  geom_text(data = n_by_gpa,\n            aes(x = GPA, y = 1.08, label = paste0(\"n=\", n)),\n            inherit.aes = FALSE, size = 2.5) +\n  scale_y_continuous(labels = percent) +\n  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 12)) +\n  scale_fill_viridis_d(option = \"C\", begin = 0.1, end = 0.9, name = \"Gender\") +\n  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +\n  labs(y = \"Proportion\", title = \"Gender\")\n\np_policy <- ggplot(survey_final, aes(x = GPA, fill = Policy_Stu)) +\n  geom_bar(position = \"fill\") +\n  geom_text(data = n_by_gpa,\n            aes(x = GPA, y = 1.08, label = paste0(\"n=\", n)),\n            inherit.aes = FALSE, size = 2.5) +\n  scale_y_continuous(labels = percent) +\n  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 12)) +\n  scale_fill_viridis_d(option = \"C\", begin = 0.1, end = 0.9, name = \"Policy_Stu\") +\n  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +\n  labs(y = \"Proportion\", title = \"Policy_Stu\")\n\np_minority <- ggplot(survey_final, aes(x = GPA, fill = Minority_Stu)) +\n  geom_bar(position = \"fill\") +\n  geom_text(data = n_by_gpa,\n            aes(x = GPA, y = 1.08, label = paste0(\"n=\", n)),\n            inherit.aes = FALSE, size = 2.5) +\n  scale_y_continuous(labels = percent) +\n  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 12)) +\n  scale_fill_viridis_d(option = \"C\", begin = 0.1, end = 0.9, name = \"Minority_Stu\") +\n  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +\n  labs(y = \"Proportion\", title = \"Minority_Stu\")\n\np_poor <- ggplot(survey_final, aes(x = GPA, fill = Poor_Stu)) +\n  geom_bar(position = \"fill\") +\n  geom_text(data = n_by_gpa,\n            aes(x = GPA, y = 1.08, label = paste0(\"n=\", n)),\n            inherit.aes = FALSE, size = 2.5) +\n  scale_y_continuous(labels = percent) +\n  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 12)) +\n  scale_fill_viridis_d(option = \"C\", begin = 0.1, end = 0.9, name = \"Poor_Stu\") +\n  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +\n  labs(y = \"Proportion\", title = \"Poor_Stu\")\n\nplot_grid(p_year, p_gender, p_policy, p_minority, p_poor, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](TE01_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nAs shown in the figure, the binary background indicators exhibit largely stable proportional patterns across GPA categories. While minor distributional shifts are observable for year of study and policy support, no pronounced polarization is evident. Overall, the visual evidence suggests limited differentiation in GPA by these binary background factors.\n\nTherefore, we next examine multi-level socioeconomic and time-use factors using heatmap to detect finer distributional shifts.\n\n### Patterns of Ordinal Background and Behavioral Variables Across GPA Categories\n\n**Multi-level Group A variables (ordinal / categorical):**\n\n- Father_Edu\n- Mother_Edu\n- Father_Occupation\n- Mother_Occupation\n- Time_Friends\n- Time_SocicalMedia\n- Time_Studying\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_heatmap <- function(df, var, x = \"GPA\"){\n  heat_df <- df %>%\n    count(.data[[x]], .data[[var]], name = \"n\") %>%\n    group_by(.data[[x]]) %>%\n    mutate(p = n / sum(n)) %>%\n    ungroup() %>%\n    rename(X = 1, Level = 2)\n  ggplot(heat_df, aes(x = X, y = Level, fill = p)) +\n    geom_tile(color = \"white\", linewidth = 0.3) +\n    scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 12)) +\n    scale_fill_viridis_c(option = \"C\", begin = 0.1, end = 0.9, direction = -1, name = \"Proportion\") +\n    theme(axis.text.x = element_text(size = 8)) +\n    labs(title = var, x = NULL, y = NULL, fill = \"Proportion\") +\n    theme_minimal() +\n    theme(\n      axis.text.x = element_text(angle = 30, hjust = 1, size = 8),\n      plot.title = element_text(face = \"bold\", size = 10)\n    )\n}\n\nmulti_vars <- c(\n  \"Father_Edu\", \"Mother_Edu\",\n  \"Father_Occupation\", \"Mother_Occupation\"\n)\n\nplots <- lapply(multi_vars, function(v) plot_heatmap(survey_final, v))\n\nplot_grid(plotlist = plots, ncol = 2, align = \"hv\")\n```\n\n::: {.cell-output-display}\n![](TE01_files/figure-html/unnamed-chunk-12-1.png){width=1344}\n:::\n:::\n\nAs shown in the heatmaps, the multi-category family background variables (parents’ education and occupation) display broadly stable composition across GPA categories. While localized shifts appear in specific cells, no clear monotonic gradient is visible in which higher parental education or a particular occupation type becomes progressively more dominant as GPA increases. Instead, most categories are represented across multiple GPA levels, suggesting that these socioeconomic indicators alone do not strongly separate learning outcomes.\n\nTherefore, we next examine students’ time-use and learning environment factors using heatmaps to identify finer distributional shifts that may be less apparent in binary comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_vars2 <- c(\n  \"Time_Friends\", \"Time_SocicalMedia\", \"Time_Studying\"\n)\n\nplots2 <- lapply(multi_vars2, function(v) plot_heatmap(survey_final, v))\n\nplot_grid(plotlist = plots2, ncol = 3, align = \"hv\")\n```\n\n::: {.cell-output-display}\n![](TE01_files/figure-html/unnamed-chunk-13-1.png){width=1344}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_mean_rank_trend <- function(df, time_vars, x = \"GPA\") {\n  trend_df <- df %>%\n    select(all_of(c(x, time_vars))) %>%\n    pivot_longer(cols = all_of(time_vars),\n                 names_to = \"TimeType\",\n                 values_to = \"Level\") %>%\n    mutate(\n      GPA = factor(.data[[x]], ordered = TRUE),\n      Level_num = as.numeric(Level)\n    ) %>%\n    group_by(GPA, TimeType) %>%\n    summarise(\n      mean_rank   = mean(Level_num, na.rm = TRUE),\n      n = sum(!is.na(Level_num)),\n      .groups = \"drop\"\n    )\n\n  ggplot(trend_df, aes(x = GPA, y = mean_rank, group = TimeType, color = TimeType)) +\n    geom_line(linewidth = 1) +\n    geom_point(size = 2) +\n    geom_text(aes(label = paste0(\"n=\", n)), vjust = -0.8, size = 3, show.legend = FALSE) +\n    scale_y_continuous(breaks = 1:5, limits = c(1, 5)) +\n    labs(\n      title = \"Mean time-use rank by GPA category\",\n      x = \"GPA category\",\n      y = \"Mean time rank (1 = lowest, 5 = highest)\",\n      color = \"Time variable\"\n    ) +\n    theme_minimal() +\n    theme(axis.text.x = element_text(angle = 30, hjust = 1))\n}\n\nplot_mean_rank_trend(raw, multi_vars2)\n```\n\n::: {.cell-output-display}\n![](TE01_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nThe heatmaps suggest gradual distributional shifts in time-use categories across GPA groups. In particular, higher GPA categories appear to contain a larger share of respondents in higher study-time levels, while lower GPA categories show relatively greater concentration in higher social media and (to a lesser extent) friends-time levels. \n\nThis visual pattern aligns with the mean-rank trend plot: the average rank for Time_Studying increases modestly with GPA, whereas Time_SocicalMedia and Time_Friends display mild downward trends as GPA rises. \n\nOverall, the combined visuals indicate a plausible association between reported time allocation and GPA categories. However, the differences are not strongly polarized, and these findings are descriptive rather than causal.\n\n\n## Relationship between Learning Outcome and Group B: Motivation/External Factors (Likert plot)\n\nBuilding on the descriptive analysis of Group A Factors, we next examine Group B Factors, which capture students’ self-reported motivation and learning environment conditions (such as training process, facilities, and perceived support from the university, lecturers, and peers). These variables are measured on Likert-type ordinal scales, so our goal is to compare response distributions rather than treat the values as continuous scores. To visualise these patterns clearly, we use Likert-style distribution plots to summarise overall agreement levels and to assess whether the composition of responses shifts across GPA categories.\n\n### Heatmap of conditional proportions\n\n::: {.cell}\n\n```{.r .cell-code}\nlikert_vars <- c(\n  \"Adapt_Learning_Uni\", \"Study_Methods\", \"SupportOf_Uni\", \"SupportOf_Lec\",\n  \"Facilitie_Uni\", \"Quality_Lecturer\", \"TrainingCurriculum\",\n  \"Competitive_Class\", \"InfuenceF_Friends\"\n)\n\nlikert_labels <- c(\n  Adapt_Learning_Uni  = \"Adaptation to university learning\",\n  Study_Methods       = \"Study methods effectiveness\",\n  SupportOf_Uni       = \"University support\",\n  SupportOf_Lec       = \"Lecturer support\",\n  Facilitie_Uni       = \"University facilities\",\n  Quality_Lecturer    = \"Lecturer quality\",\n  TrainingCurriculum  = \"Curriculum/training relevance\",\n  Competitive_Class   = \"Class competitiveness\",\n  InfuenceF_Friends   = \"Friends' influence\"\n)\n\nlikert_long <- raw %>%\n  select(all_of(likert_vars)) %>%\n  pivot_longer(cols = everything(), names_to = \"item\", values_to = \"resp\") %>%\n  filter(!is.na(resp)) %>%\n  mutate(\n    resp = as.integer(resp),\n    item_label = recode(item, !!!likert_labels),\n    resp_f = factor(resp, levels = 1:5,\n                    labels = c(\"1 -\tNot at all\", \"2 -\tLittle\", \"3 -\tModerate\",\n                               \"4 -\tQuite\", \"5 -\tVery\"))\n  )\n\n\nlikert_prop <- likert_long %>%\n  count(item, item_label, resp, resp_f) %>%\n  group_by(item, item_label) %>%\n  mutate(prop = n / sum(n)) %>%\n  ungroup()\n\nrank_top2 <- likert_prop %>%\n  filter(resp %in% c(4, 5)) %>%\n  group_by(item_label) %>%\n  summarise(top2 = sum(prop), .groups = \"drop\") %>%\n  arrange(top2)\n\nplot_df <- likert_prop %>%\n  left_join(rank_top2, by = \"item_label\") %>%\n  mutate(\n    item_label = factor(item_label, levels = rank_top2$item_label),\n    prop_div = ifelse(resp %in% c(1,2), -prop, prop),\n  )\n\nggplot(plot_df, aes(x = prop_div, y = item_label, fill = resp_f)) +\n  geom_col(width = 0.72) +\n  geom_vline(xintercept = 0, linewidth = 0.4) +\n  geom_text(\n    aes(label = ifelse(prop >= 0.06, scales::percent(prop, accuracy = 1), \"\")),\n    position = position_stack(vjust = 0.5),\n    size = 3,\n    color = \"white\"\n  ) +\n  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +\n  labs(\n    x = \"Share of responses (diverging at Neutral)\",\n    y = NULL,\n    fill = \"Response\",\n    title = \"Perceived learning environment and peer influence\",\n    subtitle = \"Diverging Likert distributions (1–5), sorted by Top-2 agreement (4–5)\") +\n  theme_minimal(base_size = 12) +\n  theme(legend.position = \"bottom\") +\n  scale_fill_viridis_d(option = \"plasma\", direction = -1)\n```\n\n::: {.cell-output-display}\n![](TE01_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nAs shown in the diverging Likert chart, responses are generally skewed toward the higher agreement levels (4–5) across most learning-environment and peer-related items, with only small proportions selecting the lowest categories (1–2). Lecturer-facing indicators (lecturer quality and lecturer support) exhibit the strongest top-2 agreement, suggesting broadly positive teaching-related perceptions in this sample. University-level conditions (facilities and university support) remain favourable but display slightly larger “moderate” shares, indicating more mixed evaluations. \n\nIn comparison, adaptation to university learning and study methods effectiveness show relatively weaker top-2 agreement and greater concentration around the middle category, implying higher heterogeneity in students’ self-perceived readiness and strategy effectiveness. Overall, the plot highlights broadly positive perceptions, while adjustment and study-method factors appear less uniformly endorsed.\n\n  \n# Summary\n\nOur visual analysis of students’ learning outcome GPA and its relationships with background characteristics, family context, time-use patterns, and perceived learning environment yielded several insights. \n\n**The key findings are:**\n\n- GPA is unevenly distributed, with most students clustered in the “Fair” and “Good” categories and relatively small groups at the extremes.\n- Demographic composition (such as gender, minority status, and financial disadvantage) shows limited variation across GPA categories in proportional comparisons.\n- Time-use patterns demonstrate clearer gradients: higher GPA categories are consistently associated with higher study-time ranks, while social-media use (and to a lesser extent time with friends) tends to be lower.\n- Family background variables (parents’ education and occupation) show observable association signals with GPA, suggesting that socioeconomic context may contribute to performance differences within the sample.\n- Perceptions of the learning environment are generally positive for teaching-related dimensions (such as lecturer quality and support, curriculum relevance, and facilities), indicating perceived strengths in institutional delivery.\n\n\n\n**Recommendations for future research:**\n\n- This work is followed the assumption that group A and B factors are independent with each other. In future, multivariate modelling can be used to evaluate the independent relationships of time-use and family background with GPA while controlling for potential confounders and interaction effects (such as different patterns across subgroups)\n- The current survey data shows potential representativeness limitations (such as gender distribution skewed towards females and under-representation of Year 1–2 students). Future data collection should aim for more balanced sampling or apply weighting to reduce bias and improve generalisability.\n- GPA value in this survey is an ordinal variable, which limits the range of visual and analytical techniques. If continuous exact numeric GPA can be collected, richer visual analyses (such as density plots, boxplots, violin plots, regression-based visualisations) and more sensitive modelling approaches can be applied.\n- GPA is the sole learning outcome indicator in this study, yet it may not be fully comparable across programmes or course structures. Future research should consider additional outcome measures (such as standardised assessments, course difficulty indicators, credits attempted, or learning engagement metrics) to reduce subjectivity and improve comparability.\n- Longitudinal designs can track same students over time to examine whether changes in time-use and learning perceptions precede GPA improvements, thereby strengthening causal interpretation beyond cross-sectional associations.\n\nBy addressing these areas, future research will strengthen the reliability of these insights and enable more nuanced analyses, ultimately supporting more targeted and equitable approaches to improving student learning outcomes.\n\n\n# References and inspiration\n\n- [Dataset of factors affecting learning outcomes of students at the University of Education,Vietnam National University, Hanoi](https://www.sciencedirect.com/science/article/pii/S2352340925001702#bib0001)\n- [Dataset about VNU students](https://data.mendeley.com/datasets/23ppcdbmhc/1)\n- [Visual Multivariate Analysis with Parallel Coordinates Plot](https://r4va.netlify.app/chap15)\n- [How to Make a Diverging Bar Chart in R](https://rfortherestofus.com/2021/10/diverging-bar-chart)\n\n\n\n\n\n",
    "supporting": [
      "TE01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}